# Identificador único (diferente al anterior)
sonar.projectKey=sistema-monitoreo

# Nombre del proyecto
sonar.projectName=Sistema Monitoreo
sonar.projectVersion=1.0

# Analizar desde la raíz, pero excluir archivos innecesarios
sonar.sources=aplicacion,Dominio,infraestructura,presentacion

# Incluir archivos TypeScript
sonar.inclusions=**/*.ts,**/*.js

# Excluir archivos innecesarios
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.spec.ts,**/*.test.ts,**/coverage/**

# Configuración del servidor (mismo que antes)
sonar.host.url=http://localhost:9000
sonar.token=sqp_ac748557aafb2cdfd4f7e4e926ad425175100d6c

# Encoding
sonar.sourceEncoding=UTF-8